# Course Project {#project}

## Teamwork and team dynamics

### Building the team contract


In your project teams:

- Discuss your thoughts on the team contract examples on Blackboard under “Content” tab
- Record your preliminary thoughts on the new issue (from
last slide)
-  Soon, you’ll create an .md file in your team’s project repo (a single contract for the whole team) called team_contract.md
- You will also finalize the contract on Wednesday
- You can start drafting the .md file today if you want to explore. If you do, link to the .md file in your new issue

### Project Team Check-Ins

Someone creates a Discussion on your team’s Github repo

- Name it “*Month Day* Team Check-in”.
- Make sure to link to it in your project log for today
  - Each member: add a comment with three bullets:
  - Something someone did to help the team this week: ___
  - Something I could have done better for the team this week: ____
  - An area/suggestion for team improvement: ____
- As a group: discuss the posts
- It’s fair to point out something someone did/didn’t do that they didn’t include at this point, but you must state it in “I” terms
- Someone replies in a new comment at the end to summarize your discussion
- Where is your team in the storming/norming/performing stages?
- You can revise your team contract as long as each team member agrees and signs via a Github commit

### Documentation Check Feedback

Clearly state in your documentation which person is primarily responsible for each task (or subtask)

- It's okay to say that one person is in charge of filling in Section 2 while another is in charge of filling in Section 3
- Another good reason to assign backups: the backup can be responsible for checking to make sure the work got done

Each person (or group of people) who does work on a task should...

1. post on that task’s issue with the details
- E.g., I revised the causal diagram for paper 4 in this commit
2. Post on the group’s “daily log”
- E.g., I worked on the paper summary task #7
 One group log said "Discussed data sets and the disconnect between the two“
- Good, but if Prof. Buzard can't see the details of what you've decidedv and/or done, she can't support you in getting to the end product you're going to need to do your analysis.
- Great examples of detailed task documentation [here](https://github.com/ecn310/course-project-tariffs/issues/7#issuecomment-3418117107) and [here](https://github.com/ecn310/course-project-tariffs/issues/5#issuecomment-3417294062).

### Documentation Structure

- Professor Buzard will look at the data and results sections holistically with data appendix and reproducibility package
  - When in doubt about whether to include data details in your report vs the data appendix/reproducibility package, ask for guidance
  - You should NOT explain exactly how you coded things in the report; just say what you did in plain English, e.g. “We merged dataset1 with dataset2 using the XYZ variable.”
  - This is flexible: depends on your project and on your preferences
- Your instructions for the reproducibility package will be the README on your reproducibility package folder if you have one, or reproducibility.md in your main folder
- Store analysis outputs in a folder on Github, so you can pull them (and link directly to them) into Overleaf



### Sketch of to-do list (mostly in order)

1. Working hypothesis with data needs specified
2. Manipulate data into the form you need
3. Run summary stats
4. Run correlations, hypothesis tests, etc.; confirm “story”
5. Write up Theory / Hypothesis
6. Write up Data, Results, Discussion sections
7. Finalize Reproducibility Package / Data Appendix
8. Expand and finalize Lit Review, References
9. Finalize Intro and Conclusion
10. Write Abstract

## Reproducibility Package

- Raw data
  - should not be modified in any way;
  - should contain all observations originally collected in a widely accessible format, with a data codebook describing all variables;
  - should have documentation about the collection of the data, such as API script or step-by-step instructions, in EXCRUCIATING detail;
- Code
  - all code required to derive analysis data from downloaded data;
  - all code required to reproduce research outputs from analysis data;
- Research outputs (graphs, tables, etc)
- README (master documentation)
  - should explain the use and structure of the code, including
  - any intermediate datasets
  - location and how to access all files, including figures
  
**What details do you need to write down?**

Ask yourself:

1. What does Professor Buzard need so she can understand exactly what we did and give us feedback?
2. What information do we need to write down so we can remember it clearly tomorrow, next week, or when we’re writing the report?
- Can be in a commit (show SHA), issue or discussion post, a file, etc.
- Example from hypothesis workshop

**Where the details live…**

Detailed documentation should be linked in your master file & your log

- Code (do-files if working in Stata)
  - Must be thoroughly commented
- Task documentation
  - I suggest Issues on Github (example here), but you can choose the location


### Reproducibility Package Ideas

[Example](https://github.com/worldbank/rio-safe-space) on Github from World Bank

- World Bank [e-book](https://worldbank.github.io/dime-data-handbook/publication.html)
  - [This section](https://worldbank.github.io/dime-data-handbook/publication.html#box-7.1-summary-publishing-reproducible-research-outputs) on output in particular
  - Great summary in this [table](https://worldbank.github.io/dime-data-handbook/publication.html#publishing-a-reproducible-research-package) specifically about the reproducibility package
  - [This](https://worldbank.github.io/dime-data-handbook/publication.html#box-7.4-releasing-a-reproducibility-package-a-case-study-from-the-demand-for-safe-spaces-project) goes along with the example above

Feodora Teti’s Comprehensive [README](https://data.mendeley.com/datasets/mbfvv936s5/1/files/38c7c07d-e571-464c-9f57-50204e149cfe)

- You can have something like this all in one document if your project is simple enough
- You should give a little bit of an introduction, like the main page of the World Bank example


Examples from previous projects [here](https://github.com/ecn310/course-project-nepobabies/blob/main/Final%20Report/ReproducibilityPackage.md), [here](https://github.com/ecn310/course-project-zipcentercrime/tree/main/Reproducibility%20Package), and [here](https://github.com/ecn310/course-project-accidentsteam/tree/main/Reproducibility%20Package).

### Reproducibility package plan

- You can put your plan wherever it makes sense to your team, just say where it is in your log and master documentation
- List all the pieces that your project requires in a plan that says where each piece will be stored and how each piece will relate to the whole
  - Github? OneDrive if any one dataset is over 50mb
  - Can it all go in a data appendix? Do you need several documents? Are all the files in one folder, or many?
- Create a timeline of the tasks required to get the reproducibility package (and underlying work) completed
  - It should dovetail with your final submission plan (which you should be updating frequently)
  - Make sure you include time to ensure do-files are well-commented
- Examples [here](https://github.com/ecn310/course-project-zipcentercrime/discussions/18) and [here](https://github.com/ecn310/course-project-taxes-tariffs/discussions/20)

### Reproducible Research Requirements

You can refer to the [World Bank's](https://worldbank.github.io/dime-data-handbook/publication.html#box-7.1-summary-publishing-reproducible-research-outputs) research handbook to obtain an understanding of these, as well.

1. Raw data should:
  a. not be modified in any way;
  b. contain all observations originally collected in a widely accessible format, with a data codebook describing all variables;
  c. have original documentation about the collection of the data, such as API script or step-by-step instructions, in EXCRUCIATING detail;
2. Raw data to research outputs section should contain
  a. all code required to derive analysis data from downloaded data;
  b. all code required to reproduce research outputs from analysis data;
c. a README with documentation on the use and structure of the code;
    i. should explain any intermediate datasets
    ii. should give location and how to access all files, including figures
3. The research report should
  a. be written and maintained as a dynamic LaTeX file
  b. be written in Overleaf
    i. .tex file can be pushed to Github from Overleaf
    ii. You’ll have to download the PDF from Overleaf and upload to Github once the report is final;
  c. [in a Data Appendix] contain instructions about where to find / how to access your reproducibility package (all your documentation, data and code);
  d. be recompiled with all final figures, tables, and other code outputs before submission.



### Master documentation file

This is a critical piece of the reproducibility package. It will encompass and contain information on every piece of your project.

- Navigate to the main page for your project repo and click "Add a README" at the bottom
  - Create the document the same as you would for any .md file on Github
- Include links to all the various pieces of your project (team contract, data, .do files, data.tex file, literature, notes, code, etc.).
  - Anything you've created (and not deleted) for the project should show up here as a link
  - It will be updated each week for anything new you create or major decisions you make
- Explain what every file in your Github repo does (this is a good time to prune your files if needed)
- Organize it by topic: keep everything related to data together, everything related to literature together, etc.
- Examples [here](https://github.com/ecn310/course-project-accidentsteam/wiki), [here](https://github.com/ecn310/course-project-diop/wiki), [here](https://github.com/ecn310/course-project-migration/wiki), and [here](https://github.com/ecn310/course-project-nepobabies/wiki)


### Full credit standard for project documentation

- All analysis is easily and fully reproduced using supplied materials.
- Documentation / reproducibility package is logically organized. Integrates data work into a coherent whole that the reader can easily follow.
  - Tell a coherent, complete story in the documentation!
- All steps, including each line (or small group of lines) of code in each do-file, are clearly explained. Key choices (e.g., how to deal with outliers) are well justified.
  - Some of this may be in report, some only in documentation
  - If in report, just point to that in documentation instead of repeating
- All sentences are complete and grammatical (or in bullet point form). All words are chosen for their precise meanings. Key concepts are completely explained. Submission has been spell-checked and proofread and has no errors.

## Project Terminology

- Reproducibility is a concept
  - Good documentation helps make a project reproducible
  - You create a reproducibility package to facilitate reproducibility
- Literature review
  - You’ve done pre-work via your paper summaries
- Analysis is a general term for your statistical work
  - Results is the title of the section of the report that talks about your analysis and what you learn from it
- Observations vs. variables
  - Observations represent the units of data that you have, like firms or people or counties. Variables are the things that you have data for each observation, e.g., a firm's revenue, a person's age, etc.
- LaTeX is the markup language we use in Overleaf
  - Overleaf is an online app that organizes and compiles LaTeX code
- You can have many different LaTeX (.tex) files in Overleaf
- Comments: % in LaTeX (# in R, * in Stata)

## Presentations

### Preliminary Results

- 3-5 minute presentation on
  - Working hypothesis
  - Null hypothesis
  - Data you use to test null hypothesis
  - Descriptive stats on each variable plus relationship between them (testing your hypothesis)
    - Include all the figures, statistics, and tables that you plan to put in your report
- Then workshop / feedback
- You can put everything into the results section of your project report (.tex in Overleaf), a Github discussion, or PowerPoint/Google Slides/etc.

### Full Presentations

Also like a workshop, lasts 5-7 minutes. It must include...

- Research question, hypothesis, null hypothesis, theory
- Your data: where it comes from, summary stats for all the variables you’re using
  - Probably graphs to give context
- Your analysis: tests of your hypothesis, anything else that’s needed to explain why this is the right test or to tell your story
- Include all the figures, statistics, and tables that you plan to put in your final report
- Same presentation formats acceptable as for the preliminary results presentations

## Rubric

[Here](https://github.com/ecn310/ClassResource/blob/main/Course_Project_Rubric.pdf) is the rubric for your final submission of the course project, including the final report and the reproducibility package.

## AI Disclosure Statements

- The AI disclosure statement is for the purposes of our coursework, so it belongs on the relevant Github issue, NOT in the report
- Be very clear about what work you’re talking about
  - “AI Disclosure Statement: No artificial intelligence was used in the process of creating this work.”
  - What is “this work”? On a Github issue, this might only apply to the single post it’s attached to
- Be detailed about what you use AI for: helping you to code, writing your code (don’t!), proofreading, troubleshoot your graphs, improving organization, etc.
- It’s fine to use no AI in a given assignment, but
  - your proofreading has to come from somewhere
  - I use Claude or ChatGPT to troubleshoot LaTeX compilation errors (full credit requires that your .tex file has zero compilation errors)
