# Data {#data}

## Project Data Check-In

You will have to write documenation for your team's project data that will include...

- Short description of the data
  - Includes number of variables, number of observations for each data set (you may have more than one data set)
- Explanation of where the data comes from / how someone can acquire it / where you have stored it
- List of key variables you may use for testing your hypothesis
  - How you will link different data sets together if necessary

You will need to answer...

Has our team already accessed all the data we need?

- (If not) Do we have a plan to access it?
- (If not) What do we need to be able to make a plan?

## Putting Together Your Data Set

Learning objectives (Greenlaw Ch. 9, pp. 160-163):

1. Develop a search strategy for finding your data (applies even if you have a dataset recommended by a faculty member)
2. Obtain data that correctly measure the concepts that your theory deems important

**Develop a search strategy for finding your data:**

In order to find data that correctly measure the concepts that your theory deems important,

- START by reviewing your theoretical model.
- ask, “What variables do I need data for to test my research hypothesis?”
- rethink your hypothesis if you can’t answer the question, “If I could obtain ideal data, what variables would they include?”

Greenlaw Ch. 9 assumes you already have your hypothesis.

- We’ll use its ideas to help you reverse-engineer a hypothesis if necessary
- To start: What variables do you have that are related to the research question?

Obtain data that correctly measure the concepts that your theory deems important. Which question should you ask as you investigate a data source?

- What data are, in fact, available?
- If the data are not good enough, are they good enough?
- If the data are not acceptable and there is no adequate **proxy**, how can the hypothesis be reformulated to make it testable, given the data available?

Proxy: a variable that substitutes for another unavailable or unobserved variable (R&vR p. 113)

- This is needed when it’s too difficult or costly to directly quantify the ideal variable, or the ideal variable is not included in available datasets


### Proxy Variables

“Proxy variables are data that we hope captures the quantitative essence of a thing without actually measuring a thing. They are used a lot in data projects, mostly because we often don’t have the data we actually want or need.” (From weallcount.com)

When you can’t directly measure the data you need, choose the best available proxy.

- GDP for standard of living
- NOT recessions for tightness of the labor market, since the unemployment rate is a better proxy

## Distinguish between types of variables

- ordinal categorical variables
- nominal categorical variables
- continuous variables on an interval scale
  - a measure that has a numerical value and the magnitude between the intervals is the same
- continuous variables on a ratio scale
  - a measure that is the same as an interval measure, but it also has a true zero value (a complete absence of what is being measured)

Table 6.1 on page 76 of Daniels & Minot is your best friend

Open Github\\exercises\\Daniels_Minot_data\\College Results.dta

• Can you find one example of each type of variable? See Table 6.1
• `label list` command is helpful

### Visualizing Variable Types

Exercise: Make appropriate use of bar graphs and histograms.

With College Results.dta open:

- `graph bar (count), over(atsp)`
  - Now try it with the “AvgNetPriceAfterGrants” variable
  - What’s going on? Use `codebook` command
- `histogram AvgNetPriceAfterGrants, percent`
  - Change the number of “bins”:
  - `histogram AvgNetPriceAfterGrants, bin(10) percent`
- What graph type would you use for variable “Size3”?
- Can you produce at least one histogram or bar chart for your project data?

## Project Data Summary Assignment (data.tex)

1. Completely customize the data.tex template for your project (don't leave any of my instructions or examples).
- This must include all six sections from my template unless you only have one data source and one data file--that is, no merging is needed
2. Provide one complete subsection in Section 2 Data Overview (provide details for each piece I included in the template) with details for each data set you are using. If you only have one dataset, you can remove the subsection command.
3. Section 3 should give both the instructions for downloading your data and also links to what you've downloaded.
4. Section 4 should point to your .do file and give a summary of any manipulation you had to do. If you don't need to merge to any more data, this is where you provide a link to the dataset that is ready for analysis.
5. If you have more than one raw data file, Section 5 says how you merge them together and this is where you provide a link to a dataset that is ready for analysis.
6. List all your key variables in Section 6. Indicate which variables are found in which datasets (subsections work well for this if you have more than one dataset).
  a. Include the type of each of your key variables (ordinal, nominal, interval scale, ratio scale) and what kind of descriptive statistics you’ll use for each variable (D&M Table 6.1)
  b. These MUST line up with the variables you specify for hypothesis testing on the hypothesis assignment.
  c. Include anything useful you've learned from the descriptive stats exercise (don't just repeat everything from your four submissions; I mean things like figuring out exactly what a variable means, that there's something strange going on with a variable that needs more investigation, etc.)
7. Ensure there are no LaTeX errors.
8. Submit AI disclosure statement on your data acquisition issue when you tell me data.tex is ready
for review.

