# LaTeX and Overleaf {#latex}

**Overleaf Logistics**

You will need to...

1. create FREE Overleaf account: https://www.overleaf.com/register
2. give Professor Buzard the email address you used to set up the account on the in-class poll: PollEv.com/kbuzard
3. Professor Buzard will give you access to your team’s Overleaf project


## LaTeX Overview

LaTeX is like a fancier version of rmarkdown. You can explore its basic commands on the [LearnLaTeX website](https://www.learnlatex.org/en/#toc).

- You have the source file where you write the “code” and then you compile/typeset it into the final product
- Final product is usually PDF
- We will use www.overleaf.com
- Structure:
  - Preamble (set options for the document)
  - `\begin{document}`
  - Body of document
  - `\end{document}`
  
Rules

- Many commands need an opening and a closing
- `\begin` paired with `\end`
- Then { paired with }. Example:
```
\begin{itemize}
\item This is the first item in a list
\item This is the second item in a list
\end{itemize}
```

- `$` to start math paired with another `$` to show where the math ends
- Others just show up alone
  - `\section`
  - `\item`
  - `\textit{text to italicize}`
  
## Overleaf Projects

Professor Buzard has created Overleaf “projects” for each of the project teams

- These are synced with your project Github repo
  - I’ve put a LaTeX template (data.tex) in your Github repo/ Overleaf project for the data summary task
- You must fill in part of this for your project that describes your data

In Overleaf,

- You can work simultaneously in Overleaf like in Google docs 
- When you’ve made a commit’s worth of progress, youbpush the changes back to Github from inside Overleaf
  - Click on “Menu” at top left, then “Github” under “Sync”
  - Then, you’ll need to pull those changes to your computer
- For Prof. Buzard's Overleaf comments, you can resolve them if you are confident you have addressed them, or you can reply to Prof. Buzard to double check. Make sure you let her know on one of your GitHub issues.
  
LaTeX write up for data.tex...

- Completely customize the data.tex template for your project for Sections 1, 2, 3, and 6 (don't leave any of Professor Buzard's instructions or examples in these sections)
- You can ignore Sections 4 and 5 for now
- Provide one complete subsection in Section 2 Data Overview (provide details for each piece I included in the template) for each data set you are considering using
- List at least four key variables in Section 6 (and potentially a dozen or more). Indicate which variables are found in which datasets (subsections work well for this if you have more than one dataset)
- Ensure there are no LaTeX compilation errors

**Troubleshooting Overleaf errors:**

- If there’s a red number immediately to the right of the “Recompile” button, click it 

**First Feedback on data.tex**

- PLEASE do things early to get feedback and improve the final submission!!!
- Overleaf
  - Double click to move to the right place in the document
  - Navigate using the table of contents
  - Make URLS into URL links, or better, embed in relevant descriptive text (just like in Markdown)
- If AI disclosure statement doesn’t make sense in a document or other submission, submit it in the relevant task issue when you say submission is ready for review

**Note on Overleaf file size limit**

- different from Github’s 100mb limit -- Overleaf's is 50mb
- It's also MUCH better practice to upload files directly to the Github file structure; otherwise, it's hard to find where that single link is on an issue

### Tables and Figures in the Report

[Insert figures](https://www.learnlatex.org/en/lesson-07) in LaTeX
[Insert tables](https://www.learnlatex.org/en/lesson-08) in LaTeX (must be customized)

```
\begin{table}[htbp]
  \caption{\textbf{enter caption here}}
  \label{tab:mlogit}
  \scriptsize
  \begin{center}
    \input{file_from_outreg.tex}
  \end{center}
  \flushleft
  \begin{footnotesize}
    \begin{singlespace}
      \textbf{Notes}: Description of your table here.
    \end{singlespace}
  \end{footnotesize}
\end{table}
```

### Tables in your presentation & report

Options for putting tables in report

1. [RECOMMENDED #1] Use [outreg2](https://libguides.princeton.edu/c.php?g=1322965&p=9734327#s-lg-box-wrapper-36285290) to output the table formatted in LaTeX ([some helpful slides](https://www.princeton.edu/~otorres/Outreg2.pdf))
- Outreg output gets stored with your other research outputs, and contents can be imported into your .tex file using the “input” command inside a table
  - Save as .tex instead of .doc
  - Use in `\input` statement from the insert table code above.
- You need to submit the command “ssc install outreg2” at the command line in Stata to install outreg
2. [RECOMMENDED #2] Represent output with figure instead of table (case specific, have to think about this)
3. [TERRIBLE IDEA] Make the table manually in LaTeX
- Instructions [here](https://www.learnlatex.org/en/lesson-08)
- This is really annoying because you have to edit it manually every time your data changes; bad for reproducibility
