# Stata {#stata}

## Coding

**What is coding?** Computer programming, or coding, is the process of issuing a series of
commands (writing instructions) that a computer (or other hardware) can
understand and execute in order to perform a task.

- Imagine a computer as being like a particularly mischievous genie; if your
instructions aren’t completely unambiguous, the computer won’t do what
you asked for
- Like a genie though, if you can get the instructions just so, you can create
magical things

## File Management

**File management** is the process of creating an organized structure to store information for easy retrieval. Proper file management practices are critical for being able to access data and code files.

-   Every file has an address on your computer, and the location is usually a series of nested folders. – When you’re coding, this address is how you tell the computer/software how to find the file – You can’t tell the computer to search for a file like you do since the computer doesn’t know what YOU think is the right file
-   If you use an Eggers 040 computer, rds.syr.edu, or any on-campus computer, **your files will travel with you if you save them to OneDrive.**
-   IMPORTANT: the default is to download files from a web browser to the Downloads folder on a computer’s hard drive. This will NOT travel with you.

## Opening Data in Stata

### Point and click: Import Wizard

These are the steps we took to open up the ECN 310 Class Survey data in Stata. You can use them to repeat that exercise, or to open up other datasets in Stata.

1.  Navigate to and open the Stata application
2.  Click on File menu, choose Import, then Text data (delimited,\*.csv,…)
3.  Browse to the location you saved the file in
4.  Change “First row as variable names” to “Custom” and “1” (this was what we did for the class survey data, note that this may not always be the option that you need)
5.  Click “OK”

Following these steps will open the file and generate the first command: `import excel`. You can see this in the history window or the output window in the middle of the screen. It will look something like...

`import excel "C:\\Users\\username\\OneDrive - Syracuse University\\Documents\\GitHub\\exercises\\application_survey_anon.xlsx", sheet("anon") firstrow`

You can then use this line of code, going forward, to import your data.

### Using a line of code

If you are opening a Stata data file with a ".dta" file extension, you can use the `use` command. If you are attempting to open a dataset in Stata that exists as a different type of file, it may be easier to open it using the Point and Click Import Wizard, and then copy that command from the history window.

1.  You must find the file path to the dataset you seek to open. Once you navigate to the file in File Explorer, you can copy and paste the path at the top of the window.
2.  You must also have the name of the file. It is best practice to copy and paste the file name and the file path instead of re-typing them yourself.
3.  Once you have those two things, you can execute the `use` command in Stata. Such as...

`use "C:\\Users\\username\\OneDrive - Syracuse University\\Documents\\GitHub\\exercises\\dataset"`

## Running Code

### Note on Stata instances

Each time you click on a file (e.g., a do-file and a data file), a new copy of Stata opens. To have both a data file and a do-file open in the same instance (copy) of Stata, you’ll need to click on one to open it, then open the other from within Stata. If you have a do-file open in one instance, and data open in a different instance, the code that you run will not operate on the data you are seeking to work with.

Note that you can NEVER have two datasets open at the same time in the same instance of Stata.

### Three ways to obtain information using Stata

1.  Execute command from a do-file
i.  Type the command in the do-file
ii. Highlight the command
iii. Hit “Control+D”

2.  Execute command in the Command Window
i.  Type the command in the Command Window
ii. Press enter

3.  Execute the command using a menu
i.  Click on the appropriate menu (e.g. Graphics)
ii. Choose the command (e.g. Pie Chart)
iii. Fill in the dialog box
iv. Click on “Submit” or “OK”

### Using do-files

Use a do-file if...

1.  You’re likely to do something similar in the future. Do-files let you save, revise, and rerun commands.
2.  You’re going the use anything your code produces. Do-files and the comments within them are a key form of documentation
3.  You’re going to share the code or product with anyone


## GSS Mini Report: Accessing & Visualizing Data

**Task**

Working in your “GSS Mini Research Report Team”:

1.  Pick one variable from the 2016 General Social Survey (GSS2016.dta) that makes sense in a pie chart
2.  Enter the variable name in PollEverywhere

-   Your team’s variable must be unique
-   Both team members should submit it

3.  Make the pie chart in Stata
4.  Save it wherever you want on your computer, as .png or .jpg (NOT as a Stata graph—nothing except Stata can open those)
5.  Go to the “First (mini) research report” issue on the exercises repo, <https://github.com/ecn310/exercises/discussions/4>
6.  Write and submit your report on the Github discussion

-   One report per team
-   Instructions are in the first post
-   I’ll put an example in the first comment on the issue

**How to access and analyze the data**

1.  Navigate to the exercises repo on Github
2.  In the list toward the left of the screen, click on GSS2016.dta
3.  Click on "View raw" or the download symbol all the way on the right of the gray "Code" bar
4.  Save the file to your computer, noting the location you save it to
5.  Navigate to where you saved the file and double-click on it (this only opens Stata because it’s a .dta)
6.  Explore the data in Stata. Use `browse` to see the data, use `describe` or `describe, short` to get a summary of the data file.
7.  Explore one variable by using `codebook varname`, where you input the name of your variable where "varname" is to get an understanding of your variable. Use `tabulate varname` to see what the observations for that variable look like.

**Make a pie graph**

-   Use `graph pie, over(worryjob)` to make a pie chart.

    -   Use `help graph pie` to view documentation on the `graph pie` command.

-   Use `graph pie, over(worryjob) title("How many people worry about losing their job?")` to add a title.

-   Use `graph pie, over(worryjob) title("How many people worry about losing their job?") plabel(_all percent)`to add percentages

-   Finally, use `graph export "C:\Users\...\pie_worryjob.png",as(png), replace` to save the graph as an image file. Ensure that you fill in the “…” to match the file path on your computer.

**Understand and apply syntax for saving a file**

-   `graph export` is the command to save a graph
-   `"C:\Users\krist\OneDrive - Syracuse University\ECN_310\pie_worryjob.png"` is the path and file name ON PROFESSOR BUZARD’S COMPUTER, not on yours! You need to customize!
-   `,` is the required comma between command and options
-   `as(png)` is the option that saves the file in PNG format
-   `replace` is the option to write over any existing file in the same location with the same name


**Mini Report Improvements**

1. Go to the “First (mini) research report” discussion on the exercises repo
2. Can anything else be improved? How about making the pie chart smaller?
3. Make .do file that produces the image in your post (detailed instructions on next slide)
4. Upload your do-file to the GSS_mini_report folder (detailed instructions in two slides)
5. As a reply (leave your original post alone!!!) to your
original comment, post improved version:
- image is smaller;
- image matches .do file;
- has new sentence at the bottom that says something like “The code that created this pie chart is here” where “here” is a link.

You will make a .do file that produces the image in your post. Professor Buzard will run it and make sure your code works/matches what’s in your post. Start by...
- Opening Stata, choose Window menu, then Do-File Editor, then New Do-File Editor
- The first line of your .do file should be the command to open the data
- Insert code to produce the same pie chart from last week
- End the file with command to save the pie chart at end
-  Save file as name1_name2.do (e.g., Dylan_Soph.do) to your computer
- Then, upload your do-file to the GSS_mini_report folder:
  - Navigate to GSS_mini report folder of the exercises repository
  - Above the list of files, select the Add file dropdown menu and click Upload files.
    - Alternatively, you can drag and drop files into your browser.
  - To select your do-file for upload, drag and drop the file, or click choose your files
  - In the "Commit message" field, type a short, meaningful commit message
  - Below the commit message fields, choose “Commit directly to the main branch”
  - Click “Commit changes”
  - Refresh the GSS_mini_report page and click on your file to make sure it looks right
  - Copy the url to add to your post on the discussion
  
  
## Outliers Exercise

**Learning Objectives:**

1. Using Log Files and Saving Your Work (Daniels & Minot, 4.5)

- Start and save a log by issuing commands at the beginning and end of a do-file.
- Understand the text, replace, and append options on the log command
- Implement best practices for saving files

2. Cleaning Data and Checking for Outliers (Daniels & Minot, 5.1 and 5.2)

- Recognize what “cleaning” your data means
- Find and fix outliers in data, clearly documenting any changes to the dataset

3. How to Make Sure Your Research Paper is Reproducible (World Bank Blogs, First paragraph, “What does reproducibility mean?“, Tip 6)
- Comprehend what reproducibility means and the main sources of reproducibility failure

**Task**

Find and fix outliers in data, clearly documenting any changes to the dataset
- Use `codebook varname` to get codebook for single variable
  - `tabulate varname` gives a table of all values
- Use `summarize varname` to get summary statistics
- If you change an outlier in any way, it MUST be documented
- DON’T just go into the data editor and change it.
  - This leaves no record; it’s legitimately TERRIBLE science. People have lost their careers over this
  - No one (including yourself or your team members) will be able to replicate your dataset if they don’t know what you did
- DO write code in your .do file like on the bottom of D&M pg. 62 (Section 5.2)
 - When doing something like this for your project, acknowledge that you’ve done it in your global documentation and point to the location in the issue to which it contributes

**Do files**

- Do file is a complete set of instructions for completing a task
- Log file is a record of how the task was executed (all the output)
  - Need to put all substantive code after the log starts
  - Log close should be at the very end
- You always experiment and learn as you build a do-file
  - Once you think your do-file is perfect, close Stata, open again, run the do-file all at once to produce a clean log without errors
  - To run the whole do-file at once, instead of highlighting one line and hitting Ctrl+D, just hit Ctrl+D with nothing highlighted
- Keep iterating until...
  - no errors when you run the .do file (1)
  - files are in the right place (2)
  - log matches your do-file exactly (3)

**Outline for the do-file you’ll create**

- `cd`
  - Once you issue the `cd` command, you don't need to type the whole path in the use and save statements
  - `cd` changes the working directory to the location you want
  - Stata will now default to looking in your new working directory to find files to open and will place things there when you save
- So, you’ll just need the file name without the file path in front of it
- If you put the file path ahead of the file name, it won’t break your code, but it’s bad for reproducibility

`log` to start the log file

`use` to open the data

[insert data analysis and modification code]

`save` to save the data

- Save the data to the same folder for this exercise as where your log, do-file, and the supplied data are 

`log close`

**Outliers Team Exercise Instructions**

- Each team’s goal
- Find and fix outliers in GSS2016_outliers.dta
  - Save a cleaned version of the .dta file (do NOT modify the original)
  - Create a .do file that executes each step
  - Use a log file to document your work; log MUST match .do file
  - Upload all three files to central Github exercises\outliers folder
    - Ensure .do file and log MATCH (that is, if I re-run your do file, I will get the same log except for my file path)

**Step 1:** (At least) One member of the team uses Github Desktop to make sure you have the most recent version of the exercises repo on your computer

**Step 2:** Create a do-file in Stata named “firstname1_firstname2_outliers.do” and save it in the exercises\\outliers folder (the version on your computer)

**Step 3:** Execute the sub-steps below with commands in your .do file:

a. Open a log (use text and replace options) in outliers folder (D&M p. 51)
– log using “[insert the path to the folder on your computer]\\firstname1_firstname2_outliers”, text replace
b. Change the path to the outliers folder using cd command (pg. 51)
c. Open GSS2016_outliers.dta (command: use)
d. Report summary stats for variable chldidel using sum command
e. Check chldidel for outliers using codebook and tabulate
f. Fix any outliers via a command in the do-file (pg. 62)
g. Run sum, codebook, and tab again to verify problem is fixed
h. Save modified data file in outliers folder as firstname1_firstname2_outliers.dta (p. 54)
i. Close log (p. 51-53) [use log close, NOT log off]

**Step 4:** Commit the three files to the outliers folder in the exercises repo using Github Desktop
a. Click “Fetch origin” and “pull origin” in top right of Github Desktop
b. Enter a descriptive commit message and click “Commit to main”
c. On web interface: make sure all three files are in the outliers folder, named correctly, and the contents of .do and log files match

**Outliers Exercise Feedback**

Look at the commit messages on exercises repo

- Look at the outliers folder on exercises repo
  - Need to follow the naming convention for the log
- Make Stata results window wider so log is easier to read
- If you lose your do file or some of its contents, your log file can save you
- Don't replace the outlier value another (more standard) value. This indicates that you know for sure that this respondent really meant they want to have 10 children
  - It’s better to make it missing (“.”)
- Remember to close everything and re-run until the do file runs cleanly so your log matches your do file

## Correlations Exercise

Learning Objectives (Daniels & Minot, Article 12.1, Section 12.3):

1. Employ and interpret scatter plots to learn about the relationship between two variables
2. Employ and interpret Pearson correlation coefficients (either `corr` or `pwcorr`), including the statistical significance of the correlation
3. Recognize the limitations of correlation analysis

Also some information in Remler & VanRyzin Ch. 2:

4. Understand and explain the concept of correlation

Employ and interpret Pearson correlation coefficients, including the statistical significance of the correlation:

The Pearson correlation coefficient, or r,...
- measures the strength of the relationship between two
continuous variables.
- is calculated using the number of observations, the values of
the variables, and the means of the variables.
- varies between -1 and +1.
- Equals 0 when there is no correlation.

This exercise has a bunch of goals:

1. Make sure you’re comfortable using Github to download and upload files
2. Become more comfortable with variables and units of analysis
3. Reinforce readings on hypotheses and theory
4. Deepen your understanding of the reading on correlations via a simple economic example
- Correlations, scatterplots, and the sign of relationships
5. Provide some examples of good code commenting
6. Help you become more comfortable with Stata do-files, logs, and file management
- You will modify an existing do file so it works on your computer
- You’ll have an example of what the log should look like

Recall the importance of reproducibility in your code (and your research paper):

The most common reasons for code to be non-transferrable are...

- the reproducibility package does not include all the required code or data files.
- the code uses file paths that only exist in the machine where they were last run.
- there are no clear instructions on what steps the reviewer should follow to recreate final results.

**Datasets**

Open up exercises\\correlations\\CPS_2017.dta

- It’s a sample of the 2017 CPS (Current Population Survey from the U.S. Bureau of Labor Statistics)
- Unit of analysis: (there is one row for) each person who was surveyed in 2017 (ages 25 to 30)
- Your data is not automatically in the unit of analysis you need
  - Example: zipcentercrime had individual 911 calls, but need to know how many 911 calls in a given area
    - They have to transform their data
- Variables: (one column for each of) 20 variables
  - age, hours, wage, earn (weekly earnings), etc.
  
**“Correlations” Exercise Requirements**

- Upload your do file and log file to the correlations
folder on the exercises repo (1 point each)
  - Point subtracted if you upload more than these two files
- Follow naming convention in instructions (1 point)
- Log should be in text format (1 point)
- Log should look just like sample_log, except it should use a directory on your computer and have the name of your log (1 point)
- Log should also match do-file (no editing the log name outside of running the do-file, or editing the log after running the do-file) (1 point)

**Step 1: Get the files from GitHub**

1. Open Github Desktop
2. Choose exercises repo
3. Click “Fetch origin” in top center of the GUI
4. Click “Pull origin” when it just said “Fetch origin”

- This brings the new files I created onto your computer

5. On Repository menu (top of Github Desktop), choose “Show in Explorer”
6. Double click on the “correlations” folder in Windows Explorer
7. Click in address bar to get path

- Copy this path (you’ll need it in a minute)

**Step 2: Save a copy of the do-file, modify, and run it**

1. Open the do-file Stata_CPS_101525.do
2. “Save as” in the correlations folder, add “YOURNAME_” to the beginning of the filename (e.g. Ryan_Stata_CPS_101525.do)
3. Replace the path after the `cd` command with the path you copied on line 23
4. Change the name of the log file (instructions in comment) on line 27
5. Run the code step by step to make sure it works and that you understand the correlations, scatterplots, and associated theories
6. Save the do-file and close Stata
7. Re-open YOUR do-file and hit “Ctrl+D” (don’t highlight anything)
8. Open YOUR log (make sure it’s a Text Document) by clicking on it in Windows Explorer to make sure it looks like MY log except the path and log name should match your path and log name

**Step 3: Upload files to Github**
1. Make sure your two files (log and do-file) show up in Github Desktop in the correlations folder on the exercises repo and are named correctly.
2. Write a substantive commit message
3. Click “Commit to main”
4. Click “Push origin” at top right
- Click “Fetch origin” and “Pull origin” first if “Push Origin” isn’t there
5. Navigate to the exercises repo on the Github UI (web interface)
6. Open the correlations folder
7. Make sure your two files (log and do-file) are there
8. Click on the do-file to make sure it looks my do-file, but with your path
9. Click on the log to make sure it looks like my log, but with your path

Notes:
- A refresher on the Github commands: [Clone / Pull / Push / Fetch](https://docs.github.com/en/repositories/working-with-files/managing-files/adding-a-file-to-a-repository)
- You can upload files directly through the Github UI if you can’t make it work in Github Desktop. Instructions [here.](https://docs.github.com/en/repositories/working-with-files/managing-files/adding-a-file-to-a-repository)

## Creating new variables

Learning objectives (Daniels & Minot Section 5.3, pp. 63-64, 67-69)

1. Use the `generate` or `gen` command to create simple new variables from the existing variables. This is the most basic, simple command for creating new variables.
2. Use the `egen` command to create a new variable by aggregating the existing data. `egen` is more powerful and a little more complicated.

Demonstration using gss_new_variables.do in exercises repo

- Best way to use this: sync your exercises repo using Github desktop, then open the do file from your machine (it will be in the main exercises folder)

## Combining datasets

[Combining datasets](https://www.stata.com/manuals/u23.pdf) (Stata Manual); [Combining datasets](https://libguides.library.nd.edu/data-analysis-stata/merge-append) (Notre Dame Hesbergh Library)

Learning objectives:

1. Recognize the usefulness of combining datasets.
2. Choose when to apply `merge` versus `append` versus `joinby` to combine datasets in Stata.
3. Employ the `merge` and `append` commands to combine datasets in Stata.

Sync the exercises repo to your machine

- Open combining_datasets folder
- Open combining_datasets_exercise.do
- You could also take a look at the excel file, but make sure to close it before running any of the code


## Different Users, Different File Paths

If you’re getting annoyed at having to change your do-file “cd” command when you switch between computers or users, I suggest putting the following where you currently have your `cd` command

```
if strpos("`c(username)'", "lgee01") {
  global path "C:\Users\LGEE01\Documents\GitHub\ParentalInvolvementRA"
  }
else if strpos("`c(username)'", "krist") {
  global path "C:\Users\krist\GitHub\ParentalInvolvementRA"
}
cd "$path“
```

Add additional `else if` statements for more users/machines.

## Creating Figures in Stata

- DON’T USE GRAPH EDITOR
  - There’s no easy way to make it reproducible
  - Use GUIs (menus) instead: https://www.theanalysisfactor.com/stata-tutorial-graphics-menu/
- Full manual when you need it: https://www.stata.com/manuals/g.pdf
- Cheatsheet: https://www.stata.com/bookstore/statacheatsheets.pdf
- Edit axis range: https://grodri.github.io/stata/graphics

## The “do” command and master do files

- If you have more than two do-files you must have a master do file
  - If you only have one do file, this is obviously silly
- This [explainer on master do-files](https://dimewiki.worldbank.org/Master_Do-files) gives an example
  - “do filename” causes Stata to execute the commands stored in filename just as if they were entered from the keyboard or in the do file directly
- If you have one do file for data preparation and another for analysis, you can

1. Instruct people two run the files in order [NOT GREAT, but
okay]
2. Paste the contents of the cleaning do file directly into the
analysis do file (okay if there are only two files both are short)
3. Create a master do file [RECOMMENDED]
  i. Put version and cd commands at top
  ii. Add do yourdofilename.do for each do file in order
